### ISSUE TITLE
Feature request: Tela inicial

### ISSUE THREAD

**Issue by brasofilo** [brcontainer/stack-exchange-notifications#1]
A tela de Welcome é legal mas só me deixa um clique atrás da informação importante.
E até agora é só uma tela vazia... 

Eu começaria pela tela que tivesse updates. 
E se houver updates de pontos e de _replies_ , então talvez começar pelos _replies_.

**Comment by brasofilo** [comment]
@brcontainer Talvez colocar nessa tela um link pra cá (support) e pros posts no Stack (official pages).

**Comment by brcontainer** [comment]
@brasofilo Você se refere as duvidas/questões em "Destaque" que aparece no stackexchange.com?

Sobre o *support* já existe um link na aba *info*, talvez eu pudesse usar para algo "publicitário", como "Fork this project" ou "Sugira está extensão para uma amigo".

O que acha?

**Comment by brasofilo** [comment]
Vai ser melhor eu maquetar a proposta, fica mais fácil discutir a respeito. Posto aqui depois

**Comment by brcontainer** [comment]
@brasofilo Adicionando mais detalhes no que era antes a "tela inicial". Um detalhe, agora a última aba da extensão que você usar vai ser a "tela inicial" e agora tem cache dessas abas, só mudando quando  chegam novas mensagens na Inbox ou quando o seu Score (achivements também) muda.
