### ISSUE TITLE
keyboard shortcut keys for preview and fullscreen

### ISSUE THREAD

**Issue by brcontainer** [brcontainer/stack-exchange-notifications#12]
Add shortcut for preview and fullscreen button in editor?

![editor](https://cloud.githubusercontent.com/assets/4368952/17518565/cd8a02b4-5e1e-11e6-9920-ccf80b9594ba.png)

Suggestions for keys?

**Comment by marcelodeandrade** [comment]
`CTRL + ALT + P` for preview
`CTRL + ALT + F` for fullscreen

**Comment by brcontainer** [comment]
@marcelodeandrade e sem o Ctrl <kbd>ALT</kbd>+<kbd>F</kbd>? Que tal?

**Comment by marcelodeandrade** [comment]
Até pensei também sem combinações menores, mas só se utilizar outras letras que não remetam um "significado" como as letras iniciais. 

O problema do <kbd>ALT</kbd>+<kbd>F</kbd> é que no Chrome ele abre o menu `settings` e no Firefox o menu `file`, será que não ocasionará conflitos?

**Comment by brcontainer** [comment]
@marcelodeandrade ocorre mesmo com o preventDefault?

**Comment by marcelodeandrade** [comment]
Não cheguei a verificar, farei isso assim que possível.

**Comment by brcontainer** [comment]
@marcelodeandrade atualizado https://github.com/brcontainer/stack-exchange-notifications/commit/744f1d97d2383870ae13214ba11dfb1e83cd7cf7#diff-5157d2e90351d3f3778d923074c14ec7R263

Os atalhos são:

- <kbd>ALT</kbd>+<kbd>F</kbd> = Normal/Fullscreen
- <kbd>ALT</kbd>+<kbd>V</kbd> = Mostrar/Ocultar pré-visualização

**Comment by marcelodeandrade** [comment]
Excelente, Guilherme! Darei uma fuçada nele, mas no Chrome vi um pequeno problema quanto desfazer a `preview`, abri a issue #14 (https://github.com/brcontainer/stack-exchange-notifications/issues/14)
