### ISSUE TITLE
Atalho do teclado não desfaz a pré-visualização

### ISSUE THREAD

**Issue by marcelodeandrade** [brcontainer/stack-exchange-notifications#14]
Ao utilizar o atalho <kbd>ALT</kbd>+<kbd>V</kbd>, implantado na versão `0.1.4`, ele não desfaz a pré-visualização no editor.

Chrome - Version 51.0.2704.106 (64-bit)

**Comment by brcontainer** [comment]
Notei isso agora, parece que ocorre em todos navegadores. É porque perde o foco do textarea, assim que possível irei corrigir.

**Comment by brcontainer** [comment]
Corrigido em https://github.com/brcontainer/stack-exchange-notifications/commit/e05df10fd5906ca5938b58b7ec83fcb8e7d3a2d8 e https://github.com/brcontainer/stack-exchange-notifications/commit/2bf56c80d7bd3fa226b278089802b546f4625e3a

**Comment by marcelodeandrade** [comment]
Tranquilo! Estou efetuando a instalação manualmente mesmo, testei e está corrigido a função do preview.

PS: A versão continua marcada como `0.1.4`

**Comment by brcontainer** [comment]
Sim só mudo pra 0.1.5 quando tem um "relase", mas estou pensando em mudar a estratégia pra evitar as pessoas se confundirem.
