### ISSUE TITLE
Botão 'Copiar para uma nova resposta' deixa de funcionar

### ISSUE THREAD

**Issue by jfbueno** [brcontainer/stack-exchange-notifications#16]
O botão de copiar o snippet para uma nova resposta deixa de funcionar quando a extensão está ativada.

O console apresenta o seguinte erro:

> Uncaught TypeError: Cannot read property 'top' of undefined

**Comment by brcontainer** [comment]
@jefhtavares Obrigado, vou verificar hoje mesmo

**Comment by brcontainer** [comment]
@jfbueno problema corrigido https://github.com/brcontainer/stack-exchange-notifications/commit/d0f49c805a16f82b310976ccca6873aa6f32f7d8

**Comment by jfbueno** [comment]
Atualizei e testei. Muito obrigado pela atenção!
