### ISSUE TITLE
Feature request: Custom links?

### ISSUE THREAD

**Issue by brasofilo** [brcontainer/stack-exchange-notifications#2]
Adoraria ter um atalho direto pro chat Estouro de Pilha.

Isso pode não ser prático por conta de usuários de outros Stacks. Talvez um item de URL customizável?

**Comment by brcontainer** [comment]
Infelizmente isto é uma limitação até mesmo na API oficial do StackExchange, no momento não é possível fazer, o que eu poderia adicionar é o link para as comunidades que você tem conta no lugar de "Welcome". O que acha?

**Comment by brasofilo** [comment]
Não lembro se dá pra usar Local Storage numa extensão de browser, vc sabe se é possível?

**Comment by brcontainer** [comment]
Sim é possível sim, no entanto existem outros "sistemas de dados" pras extensões do "Chromium", como por exemplo `chrome.storage`

**Comment by reebr** [comment]
No recurso [/sites][1] existe (entre várias informações) o Meta e o Chat de cada comunidade.

```json
...

"related_sites": [{
	"relation": "meta",
	"api_site_parameter": "meta.math",
	"site_url": "http://meta.math.stackexchange.com",
	"name": "Mathematics Meta Stack Exchange"
}, {
	"relation": "chat",
	"site_url": "http://chat.stackexchange.com?tab=site&host=math.stackexchange.com",
	"name": "Chat Stack Exchange"
}]
...
```
Se tiver como verificar em qual site o usuário está, dá para pegar o respetivo chat.


[1]:https://api.stackexchange.com/docs/sites

**Comment by brcontainer** [comment]
@brasofilo Adicionei uma tela para ter links de qualquer chat que você desejar, veja os anexos

Aqui não tem salva alguma:

![saved rooms in screen](https://user-images.githubusercontent.com/4368952/32146610-18faa058-bcc1-11e7-8bb6-578665a896a7.jpg)

Então se você tiver uma sala que gosta você pode clicar em save room:

![save room](https://user-images.githubusercontent.com/4368952/32146627-5e7a97d2-bcc1-11e7-8b0e-a19bfb1c312a.jpg)

Após salvar irá ficar assim o popup (salvei duas salas):

![saved rooms](https://user-images.githubusercontent.com/4368952/32146643-9d3c19aa-bcc1-11e7-8fd3-bad764b52ceb.jpg)
