### ISSUE TITLE
Sugestão de nova funcionalidade para automatizar a inserção de links na sessão de comentários do Stackoverflow

### ISSUE THREAD

**Issue by drmcarvalho** [brcontainer/stack-exchange-notifications#21]
O que acham de adicionar uma funcionalidade que permite automatizar a inserção de  links `Hyperlink <a>` em palavras na seção de _comentários_ de perguntas e respostas?

Seria parecido com a ferramente de Hyperlink existente no editor de perguntas e respostas do Stackoverflow, veja:

![hyperlink](https://user-images.githubusercontent.com/7807468/36631819-0f30d030-195d-11e8-8156-2664b8bcde0d.png)

Poderia ser uma caixa de dialogo como esta que é acionada quando o usuário pressiona as teclas <kbd>CTRL + L</kbd> ou <kbd>CTRL + K</kbd>, o melhor atalho pode ser decidido posteriormente.

Assim sendo, eu gostaria de ver o feedback a respeito desta sugestão?

**Comment by brcontainer** [comment]
@drmcarvalho vai para o TODO com certeza ;)

**Comment by wellmotta** [comment]
Seria interessante ter também atalhos para formatação tipo: **bold**, _italico_, e `código`.

**Comment by brcontainer** [comment]
@drmcarvalho @wellmotta demorei bastante, situações profissionais e pessoais, mas voltei com o add-on

Atalhos no campo de comentários:

- https://github.com/brcontainer/stack-exchange-notifications/blob/5517cf43a23738c0d54411ffc7721de5ac5ca16b/chrome/js/comments.js

- Firefox: já está disponível em https://addons.mozilla.org/pt-BR/firefox/addon/stackexchangenotifications/
- Opera: aguardando aprovação do moderador do Opera Developer
- Chrome: aguardando aprovação dos moderadores do WebStore devconsole
- Edge (chromium): aguardando aprovação dos moderadores do Microsoft Partner Center
