### ISSUE TITLE
Not working anymore

### ISSUE THREAD

**Issue by jdpoenisch** [brcontainer/stack-exchange-notifications#23]
Please consider getting your add-on to be signed because it is very great :)

https://support.mozilla.org/en-US/kb/add-on-signing-in-firefox

**Comment by brcontainer** [comment]
Thanks, but it's a bug in Firefox 66.0.3 and not in add-on.

This extension is signed ;)

PS: For fix this issue upgrade firefox to 66.0.4, see release notes: https://www.mozilla.org/en-US/firefox/66.0.4/releasenotes/
