### ISSUE TITLE
Feature Request: SO Chat notifications

### ISSUE THREAD

**Issue by huang-jy** [brcontainer/stack-exchange-notifications#27]
Chat notifications on SO are notoriously bad. Since we can save a room into the notifications extension, could we also get notifications on new messages? Optionally all messages or only @ mentions?

**Comment by brcontainer** [comment]
Unfortunately not. The API is limited https://api.stackexchange.com/docs.

**Comment by huang-jy** [comment]
Dang it. Well, thank you for checking and replying. I guess we can only hope they provide this function eventually. :+1:
