### ISSUE TITLE
Feature request: Latest questions by tag

### ISSUE THREAD

**Issue by elmerehbi** [brcontainer/stack-exchange-notifications#3]
Thanks for this nice extension. It would be nice to add a feature that fetches the latest questions by tags specified by the user like the add-on for [Chrome](https://chrome.google.com/webstore/detail/question-monitor-for-stac/bnnkhapbhkejookmhgpgaikfdoegkmdp) and Firefox.

**Comment by brcontainer** [comment]
@elmerehbi Thanks by your sugestion!

But this addon work using [Stack Exchange Button](http://meta.stackexchange.com/questions/tagged/stackexchange-button)

> The Stack Exchange button, also known as the Stack Exchange™ MultiCollider SuperDropdown™, refers to the button that appears at the top left of all Stack Exchange 2.0 sites.

In other words, the data that the extension access are related to all communities that have and have no way to access the data of specific communities. In this situation the data that is available in all communities are the "Inbox" and "Achivements".

Maybe in the future I try to implement the "Stackechange API", then it will be possible to do things like that. =)
