### ISSUE TITLE
Feature Request: remember previously viewed tab

### ISSUE THREAD

**Issue by gregforcey** [brcontainer/stack-exchange-notifications#4]
In 0.0.6 this extension always opens to the about (info) tab when it is clicked. Could you allow this extension to remember the last tab that was viewed (achievements or inbox) so that it opens to that the next time it is clicked?

Another option could be a preference to select which tab the extension would show by default when it is clicked. 

Appreciate you working on this and offering it for Opera. I'm finding it very useful!

**Comment by brcontainer** [comment]
Thanks for the suggestions, it will be released soon.

**Comment by brcontainer** [comment]
@gregforcey News:

- Added "reminder tab"
- Added "tab cache"
- Release version to Firefox

**Note:** "Opera addons" and "Mozilla addons" are reviewing before approving the publication, It may take a few days to publish the new version (0.0.8), see details: https://github.com/brcontainer/stack-exchange-notifications/commit/70df71acac202e388f3bb334ce460674653133de

**Comment by brcontainer** [comment]
Published version 0.0.8:

- https://addons.opera.com/en/extensions/details/stackexchange-notifications/
- https://addons.mozilla.org/en-US/firefox/addon/stackexchangenotifications/

**Comment by gregforcey** [comment]
Excellent. Caching is working perfectly!
